### ISSUE TITLE
A Case For Markdown, no underline

### ISSUE THREAD

**Issue by salcode** [mcdwayne/PublicDocs#1]
On https://www.mcdwayne.com/2018/05/24/the-case-for-markdown/, the following renders as __bold__, not underline.

```
Do you want to underline something?  __word__  
```

In my experience, I've not seen underline in markdown, probably because of the confusion it could cause with links.

You could change this to

```
Do you want to something in italics?  _word_  
```

**Note**: I do think it is odd that both `**word**` and `__word__`, render as bold but that [seems to be part of the markdown standard](https://daringfireball.net/projects/markdown/syntax#em)

**Comment by mcdwayne** [comment]
Thanks Sal!  

That is a very valid point.  
I consulted https://en.support.wordpress.com/markdown-quick-reference/ and that has no underline at all.  I am going to fix this to avoid future confusion.  Will be changing it to italics per your suggestion.  

I had not even considered the use case of fixing content issues from Github and using wp-cli post update to deploy fixes, but now I think I am going to explore that!  

THANK YOU!

**Comment by salcode** [comment]
I haven't done any publishing via WP CLI, sounds cool. Thanks for writing this article.

**Comment by mcdwayne** [comment]
Dude, check this out:  https://github.com/mcdwayne/postit
only works on Pantheon (at the moment) but that is the only use case this was built for :)
